### ISSUE TITLE
adjust known_hosts strategy

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#24]
https://github.com/whilp/ssh-agent/issues/2#issuecomment-220899658

This change will require us to adjust our setup of `known_hosts`

**Comment by rosskevin** [comment]
```
Running `docker run --rm --volumes-from=afcorefoo1_ssh_agent -v ~/.ssh:/ssh whilp/ssh-agent:latest ssh-add /ssh/id_rsa`
Error connecting to agent: No such file or directory
/Users/kross/projects/docker-rails/lib/docker/rails/app.rb:262:in `exec': Failed to execute: `docker run --rm --volumes-from=afcorefoo1_ssh_agent -v ~/.ssh:/ssh whilp/ssh-agent:latest ssh-add /ssh/id_rsa` (RuntimeError)
        from /Users/kross/projects/docker-rails/lib/docker/rails/app.rb:383:in `block in ssh_add_keys'
        from /Users/kross/projects/docker-rails/lib/docker/rails/app.rb:380:in `each'
        from /Users/kross/projects/docker-rails/lib/docker/rails/app.rb:380:in `ssh_add_keys'
        from /Users/kross/projects/docker-rails/lib/docker/rails/app.rb:215:in `run_ssh_agent'
        from /Users/kross/projects/docker-rails/lib/docker/rails/cli/ssh_agent.rb:7:in `forward'
```

**Comment by rosskevin** [comment]
I don't have any real security concerns to have this extra container running with the upkeep.  I'm going to yank this code and if you need ssh, mount volume `~/.ssh:/root/.ssh` into the target container.
