### ISSUE TITLE
Networks are not being cleaned up - `could not find an available predefined network`

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#28]
After a few runs, it seems that networks are being left up. https://github.com/docker/docker/issues/23971#issuecomment-245247714

Here is the `ci` error:

``` bash
failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
/home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/lib/docker/rails/app.rb:267:in `exec': Failed to execute: `docker-compose -f docker-compose-1paralleltests232.yml -p 1paralleltests232 up --abort-on-container-exit` (RuntimeError)
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/lib/docker/rails/app.rb:276:in `exec_compose'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/lib/docker/rails/app.rb:164:in `up'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/lib/docker/rails/cli/main.rb:72:in `up'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/lib/docker/rails/cli/main.rb:28:in `ci'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/gems/docker-rails-1.0.0/bin/docker-rails:9:in `<top (required)>'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/bin/docker-rails:23:in `load'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/bin/docker-rails:23:in `<main>'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/bin/ruby_executable_hooks:15:in `eval'
        from /home/apps/.rvm/gems/ruby-2.3.1@af/bin/ruby_executable_hooks:15:in `<main>'
```

``` bash
apps@camacho:~$ docker network ls
NETWORK ID          NAME                        DRIVER              SCOPE
c6bc23e13cb1        131paralleltests1_default   bridge              local               
37bb876607ec        131paralleltests2_default   bridge              local               
e149cba2595f        131paralleltests3_default   bridge              local               
efa5fbe0eaf5        131paralleltests4_default   bridge              local               
5d010e72ea4a        131paralleltests5_default   bridge              local               
9a0e616fea83        131paralleltests6_default   bridge              local               
8d96b8fa8a53        131paralleltests7_default   bridge              local               
8922b222de91        131paralleltests8_default   bridge              local               
34873aab6a9f        131paralleltests9_default   bridge              local               
60dc3edc5d2c        1paralleltests210_default   bridge              local               
c367d0b9cc63        1paralleltests231_default   bridge              local               
01b9b3c33b84        1test209_default            bridge              local               
1f5e46cfb572        1test211_default            bridge              local               
0aa8bc67e25a        1test212_default            bridge              local               
db2c21c0db26        1test213_default            bridge              local               
fb12a858ef31        1test214_default            bridge              local               
1ffc0f5778a5        1test217_default            bridge              local               
b7fbf11d58a2        1test218_default            bridge              local               
4c46f4911e96        1test219_default            bridge              local               
f0612fd527ad        1test220_default            bridge              local               
3988c5e832aa        1test221_default            bridge              local               
6775fbd47866        1test222_default            bridge              local               
e4dcf7461dc6        1test223_default            bridge              local               
b0b2bd9c95ac        1test224_default            bridge              local               
b4a0921e6a4e        1test225_default            bridge              local               
5b254cc320c0        1test226_default            bridge              local               
7d2fc021ece1        1test227_default            bridge              local               
f4a34919833b        1test228_default            bridge              local               
512ca1da976d        1test229_default            bridge              local               
a980cd1737ae        1test230_default            bridge              local               
f26a9f8c0488        bridge                      bridge              local               
95a90c209295        host                        host                local               
23bb2895ba1e        none                        null                local 
```

It seems that we aren't cleaning up networks for some reason.

Docs: https://docs.docker.com/compose/networking/

**Comment by rosskevin** [comment]
It seems that perhaps we need to run `docker-compose down`.

related: https://github.com/buildkite/agent/issues/277

**Comment by rosskevin** [comment]
workaround cleanup command:
`docker network ls | grep paralleltests | awk '{print $1}' | xargs docker network rm || echo "Ignoring docker network rm failure"` 

Will cleanup `paralleltests`.

**Comment by rosskevin** [comment]
It looks like with this change we can remove some things we had to do manually before.  This affects:
- image cleanup
- volume cleanup
- stop command
